# Dependencies
# markdown:            redcarpet
# highlighter:         pygments
highlighter:         rouge

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: false

# Setup
title:            oiwfm
tagline:          '' # Learning to be Giant.
description:      'Some notes about wa and math.'
url:              http://dm-akulich.github.io

author:
  name:           'Dima'
  url:            http://dm-akulich.github.io
  gravatar:       https://en.gravatar.com/yourname
  photo:          http://2.gravatar.com/avatar/00000000000000000000000000000000?size=350
  introduction:   '' # Some introduction words that will be displayed under the avatar. You may include HTML <a href="#">here</a>.

paginate:         15
paginate_path:    '/blog/page:num'

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/dm-akulich/dm-akulich.github.io
